services:
  redis:
    image: redis:7.0-alpine
    container_name: redis
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 15s
      timeout: 3s
      retries: 4
    ports:
      - "6379:6379"
    networks:
      - rate-limit

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    ports:
      - "8080:8080"
    networks:
      - rate-limit
    depends_on:
      redis:
        condition: service_healthy

networks:
  rate-limit:
